### PR TITLE
sr: Add ray-tracing types and deduce OpPhi type in a consistent way

### PR DESCRIPTION
**Pull request by MarijnS95**
While randomly trying out `sr` to see what data would come out of it I ran into these issues, thought it was only fair to submit the fixes :)

### CODE REVIEW

**Review by khyperia — APPROVED** [review]
Not sure about the OpPhi change because I don't use SR (mostly wanting the content of #187 to be merged), but it looks sane to me!

**Comment by MarijnS95** [comment]
@khyperia Thanks! I can move the OpPhi change to a separate PR since squash-merging would make a mess of that history anyway :)

**Comment by khyperia** [comment]
eh, should be fine! pretty sure the change is okay, I just don't know the quirks of SR and can't 100% say it's correct, just 95% :P

**Comment by MarijnS95** [comment]
Was already moving it over to a separate PR :)

**Pull request merged**
