### PR TITLE
Implement `Clone` for `dr::Module`

### PR DESCRIPTION
**Pull request by DasEtwas**

### CODE REVIEW

**Comment by Jasper-Bekkers** [comment]
Nice we were actually looking at this today as well. Would be nice to know why this wasn't done yet, @kvark maybe you know?

**Comment by kvark** [comment]
I recall no reason for this to not be done, other than that nobody bothered or needed that yet.

**Comment by Jasper-Bekkers** [comment]
Alright lets merge it in then 👍

**Comment by DasEtwas** [comment]
now that was QUICK. thanks!

**Pull request merged**
